name: CICD

on :
  push:
    branches:
      - ci-setup

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        working-directory: ./tests
        run: |
          make unit-test
          make integration-test

      - name: Clean
        working-directory: ./tests
        run: make clear

