name: Test

on :
  push:
    branches:
      - master
      - dev
      - integration-test-fix
  pull_request:
    branches:
      - master
      - dev
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup config for test
        run: sudo cp -r tests/build/etc/trasa /etc/trasa

      - name: Create necessary directories
        run: |
        sudo mkdir -p /var/trasa/minio
        sudo chmod 777 /var/trasa/minio
        sudo mkdir -p /var/trasa/thg
        sudo chmod 777 /var/trasa/thg
        sudo mkdir -p /tmp/trasa/trasagw
        sudo chmod 777 /tmp/trasa/trasagw

      - name: Unit Test
        working-directory: ./tests
        run: make unit-test

      - name: Integration Test
        working-directory: ./tests
        run: make integration-test

      - name: Clean
        working-directory: ./tests
        run: make clear


